[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unlicense",
  "Apache-2.0 WITH LLVM-exception"
]

[advisories]
ignore = [
  "RUSTSEC-2024-0436"  # Игнорируем проблему с paste
]